// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYQk5ndgyRQVBPn4eu9cD6TfESgxyrd-g',
    appId: '1:124297676738:web:d7eacf9198e89b0c53b85b',
    messagingSenderId: '124297676738',
    projectId: 'fir-notes-642ba',
    authDomain: 'fir-notes-642ba.firebaseapp.com',
    storageBucket: 'fir-notes-642ba.appspot.com',
    measurementId: 'G-VXJ3V31RTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtHzkh9SsIa7rW5IRn59zB4xy1Wx4ytA',
    appId: '1:124297676738:android:44f7b8e6c1d6665953b85b',
    messagingSenderId: '124297676738',
    projectId: 'fir-notes-642ba',
    storageBucket: 'fir-notes-642ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZzx_hlUm5OhiQnDXZgRW41-v-Tv1adwQ',
    appId: '1:124297676738:ios:81f27cadf6d6a25453b85b',
    messagingSenderId: '124297676738',
    projectId: 'fir-notes-642ba',
    storageBucket: 'fir-notes-642ba.appspot.com',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZzx_hlUm5OhiQnDXZgRW41-v-Tv1adwQ',
    appId: '1:124297676738:ios:4c0dd7ef3957d29c53b85b',
    messagingSenderId: '124297676738',
    projectId: 'fir-notes-642ba',
    storageBucket: 'fir-notes-642ba.appspot.com',
    iosBundleId: 'com.example.firebaseNotes.RunnerTests',
  );
}
